### ISSUE TITLE
Test relative-IRI resolution base inconsistent with expected results

### ISSUE THREAD

**Issue by gkellogg** [w3c/rdf-tests#106]
Some tests, e.g., `rdf-turtle/turtle-subm-01.ttl` expect to be evaluated against the original test-suite location `http://www.w3.org/2013/TurtleTests/`. The result files are consistent with the (previous) location in `https://w3c.github.io/rdf-tests/turtle/`, instead.

See https://github.com/w3c/rdf-tests/blob/4e2e64b5b4a859b7326018c7ae8fe0a0b4b7fcbb/rdf/rdf11/rdf-turtle/README#L34-L41.

Either results need to be changed back to be relative to `http://www.w3.org/2013/TurtleTests/`, or the new location of `https://w3c.github.io/tests/rdf/rdf11/rdf-turtle/`.

**Comment by afs** [comment]
Minor preference for `https://w3c.github.io/tests/rdf/rdf11/rdf-turtle/` because `rdf-tests` is not the same as RDF 1.1 WG blessed test area.
