### ISSUE TITLE
testing rdf:JSON

### ISSUE THREAD

**Issue by pfps** [w3c/rdf-tests#139]
How will rdf:JSON be tested?

**Comment by pfps** [comment]
Closing because this repository is not connected to the RDF-star WG bulletin board.

**Comment by afs** [comment]
https://github.com/w3c/rdf-star-wg/issues/125

**Comment by afs** [comment]
This is a community effort.

Tests get written and a PR submitted.

Contributions welcome.

**Comment by TallTed** [comment]
@pchampin -- 

Please see https://github.com/w3c/rdf-tests/issues/139#issuecomment-2198105744.

Please add this repo (w3c/rdf-tests) to the [RDF-star WG project dashboard](https://github.com/orgs/w3c/projects/20/).

**Comment by pchampin** [comment]
> Please add this repo (w3c/rdf-tests) to the [RDF-star WG project dashboard](https://github.com/orgs/w3c/projects/20/).

It is already connected, but only PRs are included in the dashboard... I searched the minutes but didn't find any recorded rationale for that (although [my action](https://github.com/w3c/rdf-star-wg/issues/81) was explicitly about the PRs). I suspect that we considered that many issues in this repo were not in scope for the RDF-star WG...

We can always change our mind, of course.

**Comment by gkellogg** [comment]
Maybe there’s a way to use issue tags to filter those that show up in our dashboard. We need to synchronize over more RDF-star issue labels, too.
