### ISSUE TITLE
mf:conformanceRequirement is not defined

### ISSUE THREAD

**Issue by timrdf** [w3c/rdf-tests#14]
[sparql11/data-sparql11/manifest-all.ttl](https://github.com/w3c/rdf-tests/blob/gh-pages/sparql11/data-sparql11/manifest-all.ttl#L56) uses the term [mf:conformanceRequirement](http://www.w3.org/2001/sw/DataAccess/tests/test-manifest#conformanceRequirement), but it is not defined at http://www.w3.org/2001/sw/DataAccess/tests/test-manifest#.

```
@prefix mf:     <http://www.w3.org/2001/sw/DataAccess/tests/test-manifest#>
....
<http://www.w3.org/TR/sparql11-query/> rdfs:label "SPARQL 1.1 Query Language" ;
	mf:conformanceRequirement (
		<aggregates/manifest.ttl>
```

**Comment by gkellogg** [comment]
See PR #17.
