### ISSUE TITLE
SPARQL 1.1 entailment RIF qt:data files missing

### ISSUE THREAD

**Issue by timrdf** [w3c/rdf-tests#15]
In [data-sparql11/entailment/manifest.ttl](https://github.com/w3c/rdf-tests/blob/gh-pages/sparql11/data-sparql11/entailment/manifest.ttl), although

[:rdfs13's rdfs13.ttl](https://github.com/w3c/rdf-tests/blob/gh-pages/sparql11/data-sparql11/entailment/manifest.ttl#L571) exists at [entailment/rdfs13.ttl](https://github.com/w3c/rdf-tests/blob/gh-pages/sparql11/data-sparql11/entailment/rdfs13.ttl),

[:rif01's rif01.ttl](https://github.com/w3c/rdf-tests/blob/gh-pages/sparql11/data-sparql11/entailment/manifest.ttl#L582) does not exist at [entailment/rif01.ttl](https://github.com/w3c/rdf-tests/blob/gh-pages/sparql11/data-sparql11/entailment/rif01.ttl) (within [entailment/](https://github.com/w3c/rdf-tests/tree/gh-pages/sparql11/data-sparql11/entailment))

Similarly for the other five RIF tests in the same manifest.

**Comment by gkellogg** [comment]
They must not have been in the zip file used to initialize the repo. I found them at http://www.w3.org/2009/sparql/docs/tests/data-sparql11/entailment/, however. Let me know if you find any more missing.

**Comment by timrdf** [comment]
Thanks, @gkellogg.

I do not see any more missing files for dawgt:approved mf:QueryEvaluationTests.

Regards,
Tim
