### ISSUE TITLE
Add RDFa syntax tests

### ISSUE THREAD

**Issue by csarven** [w3c/rdf-tests#2]

**Comment by gkellogg** [comment]
@csarven, the RDFa tests live at https://github.com/rdfa/rdfa-website/tree/master/tests, and online at http://rdfa.info/test-suite/. Do you think they need to be moved here?

**Comment by csarven** [comment]
No, not particularly. I was under the impression that all tests would be handled here from here on end. I have no preference either way in this case. Feel free to close this issue if they will not be moved here.

**Comment by gkellogg** [comment]
They may need curation, but in particular in the case of RDFa tests, they probably live in the best place. However, a link from the main index page would be useful. For JSON-LD too.
