### ISSUE TITLE
Escaping "." in the localName_with_non_leading_extras turtle parsing test case

### ISSUE THREAD

**Issue by robstewart57** [w3c/rdf-tests#26]
I have a question about "." being escaped in the localName_with_non_leading_extras turtle parser test case. The input ttl file is:

@prefix p: <http://a.example/>.
p:a·̀ͯ‿.⁀ <http://a.example/p> <http://a.example/o> .

In the expected case in the nt file, this subject URI is translated to:

    <http://a.example/a\u00b7\u0300\u036f\u203f\u002e\u2040>
    <http://a.example/p> <http://a.example/o> .

Why is the "." character escaped to \u002e ?

I would expect the subject URI to be escaped to:

    <http://a.example/a\u00b7\u0300\u036f\u203f.\u2040>

The input and expected output test cases are:

http://www.w3.org/2013/TurtleTests/localName_with_non_leading_extras.ttl
http://www.w3.org/2013/TurtleTests/localName_with_non_leading_extras.nt

This question appears to have been asked before on this list, back in December 2013 by David Robillard:

https://lists.w3.org/Archives/Public/public-rdf-comments/2013Dec/0115.html

For this W3C RDF turtle test case, should "." be escaped to \u002e or should it not be escaped?

This GitHub issue is carried from https://lists.w3.org/Archives/Public/public-rdf-comments/2015Nov/0002.html .

**Comment by afs** [comment]
There is no requirement for it to be escaped -- see [section 6](http://www.w3.org/TR/n-triples/#n-triples-mediatype) where it says characters outside ASCII must be escaped for use in `text/plain`.

There is no requirement to escape any of the characters - N-Triples is defined using UTF-8 these days. See [section 4](http://www.w3.org/TR/n-triples/#canonical-ntriples) on the canonical form.

**Comment by robstewart57** [comment]
Hi @afs ,

So to be clear, on expected RDF graph in-memory, according to https://github.com/w3c/rdf-tests/blob/gh-pages/turtle/localName_with_non_leading_extras.nt in this repository is:

    <http://a.example/a\u00b7\u0300\u036f\u203f\u002e\u2040> <http://a.example/p <http://a.example/o> .

Are you saying that this is an incorrect expected outcome, i.e. the localName_with_non_leading_extras.nt in this repository should change? Or are you saying that both

    <http://a.example/a\u00b7\u0300\u036f\u203f\u002e\u2040>

and

    <http://a.example/a\u00b7\u0300\u036f\u203f.\u2040>

Are equally valid test successes for the subject in the in-memory RDF graph once the turtle file is parsed?

**Comment by afs** [comment]
Are you really asking about passing the test?

Test success is defined by the two graphs from the Turtle parsing and the N-Triples parsing being the same graph.  See [RDF 1.1 Testcases - section 2.2](http://www.w3.org/TR/rdf11-testcases/#evaluation-tests) - the two graphs/datasets are isomorphic to pass the test. 

So, logically, parse both files and see if the resulting graphs are isomorphic. That is by far the best way to check for test correctness; how the N-triples is written `\u` or `http://a.example/a·̀ͯ‿.⁀` is not important - the parser will have sorted it out.  An IRI is a sequence of Unicode codepoints so it is `http://a.example/a·̀ͯ‿.⁀`.

Comparing the output with the N-Triples form requires other assumptions unrelated to the test but if you must do it that way (and be careful about blank nodes), then parse and output the N-triples as well.  

As both sides of the comparison are written by the same engine, presumably the way IRIs are written is the same.  Ditto whitespace.
