### ISSUE TITLE
Understanding the effect of rdf:resource with xml:base in test xmlbase-test002

### ISSUE THREAD

**Issue by robstewart57** [w3c/rdf-tests#44]
Where should I be looking in the RDF/XML specification to understand
test xmlbase-test002?

The file xmlbase/test002.rdf is:

```
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
         xmlns:eg="http://example.org/"
         xml:base="http://example.org/dir/file">
 <rdf:Description>
   <eg:value rdf:resource="relFile" />
 </rdf:Description>
</rdf:RDF>
```

And the expected parsed triple (in xmlbase/test002.nt) is:

    _:j0 <http://example.org/value> <http://example.org/dir/relFile> .

Where should I look to understand why xml:base :

http://example.org/dir/file

Is modified when expanded with rdf:resource="relFile" to:

http://example.org/dir/relFile

Where `file` has been replaced with `relFile`.

**Comment by gkellogg** [comment]
Relative IRI resolution is pretty common between RDF specs, and the actual algorithm comes from RFC 2396. See [section 5.3](https://www.w3.org/TR/rdf-syntax-grammar/#section-baseURIs), which also references [XML Base](https://www.w3.org/TR/xmlbase/).

This is probably not the best place to ask for general questions on RDF serializations. You might, instead, send questions to semantic-web@w3.org, or try the #swig channel on irc.freenode.net.
