### ISSUE TITLE
Error 404 for the test-update schema

### ISSUE THREAD

**Issue by BorderCloud** [w3c/rdf-tests#50]
Hi

Test-update schema's link is dead :
http://www.w3.org/2009/sparql/tests/test-update#  (prefix ut)

Bye
Karima

**Comment by gkellogg** [comment]
A copy of the vocabulary is at [1], there may be an Apache configuration missing, perhaps one of the former SPARQL WG team members can fix.

Gregg Kellogg

[1] https://www.w3.org/2009/sparql/docs/tests/test-update.n3

**Comment by BorderCloud** [comment]
Thanks. 
May be, it's the moment to do a backup of all these schemas in this project.

**Comment by gkellogg** [comment]
Good idea, a PR would be welcome, but if you haven’t already, you might consider joining the CG.

**Comment by BorderCloud** [comment]
Before a PR, we need  to rewrite the definitions of prefixes in a final draft of test cases and we can after change easily all these prefixes in all the files. 

For the moment this 404, it's not a problem to execute the tests.

**Comment by gkellogg** [comment]
The definitions of prefixes have been stable for years, and at this point it’s inpractical to change them. The repository exists to preserve the sources and provide some means to fix or add new tests. It would be great if they were synchronized back to w3 space, but it’s been hard to get staff resources to make it happen.
