### ISSUE TITLE
subquery13 

### ISSUE THREAD

**Issue by dinikolop** [w3c/rdf-tests#54]
Looking at the manifest file of subquery tests for sparql 1.1 and more specifically at subquery 13:
https://github.com/w3c/rdf-tests/blob/b3136e909c6f1bfa550290bfb6cc41a29f2dc40d/sparql11/data-sparql11/subquery/manifest.ttl#L152-L160

noticed that it points to query, data and result set files of subquery 11:

```rdf
mf:action 
        [ qt:query  <sq11.rq> ; 
          qt:data   <sq11.ttl> ] ; 
   mf:result  <sq11.srx> 
```
Is this a mistake?
Thanks!

**Comment by gkellogg** [comment]
Yes, I've noticed a couple of places where the actual query and data used for a test entry aren't right; however, these are the tests run by implementations claiming conformance.

This group, can of course, decide to update the test to reference sq13, if there is concurrence. Best done through a PR.

**Comment by afs** [comment]
I think we should fix this - we are adding tests anyway so the repo is not an exact reflection of the original implementation reports. It is a balance; in this case I don't think this is a controversial area of conformance (risky to say that!). If in doubt add tests, but here it looks like a simple mistake.

@gkellogg - any others you know of?

**Comment by afs** [comment]
Let's close this and open new issues for new problems.
