### ISSUE TITLE
How to run the constructwhere04 test?

### ISSUE THREAD

**Issue by wouterbeek** [w3c/rdf-tests#55]
Test `constructwhere04` has the following query:

```rq
PREFIX : <http://example.org/>

CONSTRUCT 
FROM <data.ttl>
WHERE { ?s ?p ?o }
```

^ This instructs the SPARQL engine to look for a file or graph called `data.ttl`, but since this is a relative URI the engine cannot find the file.

Since it is not possible to set a specific base URI when running a SPARQL query, and since modifying the SPARQL query to include a `BASE` clause seems dirty/unintended, what would be the appropriate way to run this particular test?

**Comment by afs** [comment]
data.ttl should be in the same directory as the query. Reading the test query will have the query as the base URI, so `<data.ttl>` is resolved against that - same directory.

**Comment by wouterbeek** [comment]
@afs I don't understand the following part:

> data.ttl should be in the same directory as the query.

The data graphs are loaded into a SPARQL endpoint.  Once loaded into the SPARQL endpoint, the directory structure from which the data was uploaded is no longer available.  This is not a problem for data since a base URI can be specified when uploading (and that makes all relative IRIs absolute).

Unfortunately, the same does not apply to queries:

> Reading the test query will have the query as the base URI

According to [this SPARQL Protocol 1.1 section](https://www.w3.org/TR/sparql11-protocol/#base-iri) it is not possible to specify a base URI when evaluating a SPARQL query.  The only way in which a base URI can be specified is by changing the SPARQL query string, either by inserting a `BASE` clause or by changing relative IRIs to absolute IRIs, but this latter approach is very complex (it requires parsing the query string, manipulating the AST, and then generating the new query string).

**Comment by gkellogg** [comment]
"Directory" is a little misleading. Relative URLs are resolved according to [RFC3986](https://tools.ietf.org/html/rfc3986). The query lives at a URL http://w3c.github.io/rdf-tests/sparql11/data-sparql11/construct/constructwhere04.rq. The `data.ttl` relative URL is resolved using that location to come up with http://w3c.github.io/rdf-tests/sparql11/data-sparql11/construct/data.ttl. See [Reference Resolution](https://tools.ietf.org/html/rfc3986#page-28) for the algorithm.

**Comment by afs** [comment]
The test suite is (implicitly) being executed locally - not via the SPARQL protocol. Reading the query, from file or URL, will cause the base URI to be set per RFC3986 and then `<data.ttl>` resolves to a URL.

If you want to execute the test suite in other set ups, your example being sending the query over the SPARQL protocol to a remote query processor, then some adaptation will be needed.

**Comment by wouterbeek** [comment]
Thanks for looking into this, I think this issue has been sufficiently answered / can be closed.
