### ISSUE TITLE
SPARQL test suite missing coverage of XPath Constructor Functions

### ISSUE THREAD

**Issue by kasei** [w3c/rdf-tests#66]
It looks like the [original DAWG tests](https://github.com/w3c/rdf-tests/tree/gh-pages/sparql11/data-r2/cast) only covered testing that the values resulting from a cast had the correct datatype, not the expected value. So, for example, an implementation could say `xsd:boolean("0")` evaluated to `true` and still pass the test suite.

I'm working on a PR to add some tests to improve coverage in this area.

**Comment by kasei** [comment]
@afs – This is partly motivated by finding that Jena seems to disallow casting numerics others than `xsd:integer` to `xsd:boolean`. I *think* that [F&0 2.0 §17.1.6](https://www.w3.org/TR/2007/REC-xpath-functions-20070123/#casting-boolean) is the normative reference here:

> * If ST is xs:float, xs:double, xs:decimal or xs:integer and SV is 0, +0, -0, 0.0, 0.0E0 or NaN, then TV is false.
> * If ST is xs:float, xs:double, xs:decimal or xs:integer and SV is not one of the above values, then TV is true.

If you agree, can you confirm that I've understood Jena's implementation of the boolean casting correctly?

**Comment by afs** [comment]
I agree that Jena's implementation is not casting numerics correctly.

BTW - generally - can refer to F&O latest even if the spec if technically F&O 2.x because the desire in the SPARQL 1.2 issues is to update.

https://www.w3.org/TR/xpath-functions/#casting-boolean

**Comment by kasei** [comment]
@afs – Yeah, I had been relying on 3.1, but wanted to link to 2.0 just in case there were any differences that might explain the behavior. They seem the same to me, but I haven't read them closely to spot any divergence.

**Comment by kasei** [comment]
As #68 was merged, I'm going to close this.
