### ISSUE TITLE
Commented out tests in the rdf-xml test suite

### ISSUE THREAD

**Issue by aucampia** [w3c/rdf-tests#80]
There are some tests in the RDF/XML test suite that are commented out:

- https://github.com/w3c/rdf-tests/blob/d2cc355bf601d8574116f3ee76ca570925f35ac3/rdf-xml/manifest.ttl#L54
- https://github.com/w3c/rdf-tests/blob/d2cc355bf601d8574116f3ee76ca570925f35ac3/rdf-xml/manifest.ttl#L57
- https://github.com/w3c/rdf-tests/blob/d2cc355bf601d8574116f3ee76ca570925f35ac3/rdf-xml/manifest.ttl#L63
- https://github.com/w3c/rdf-tests/blob/d2cc355bf601d8574116f3ee76ca570925f35ac3/rdf-xml/manifest.ttl#L162-L165

Is there any reason why they are commented out? I ask because I reworked the RDF/XML test suite for python RDFLib and I noticed a drop in coverage which at least in part relates to XML Literals which are in the commented out tests:

- https://github.com/RDFLib/rdflib/pull/1987#issuecomment-1146855204

To get hits from search engines, the URIs for the commented out tests are:

- `http://www.w3.org/2013/RDFXMLTests/#rdfms-empty-property-elements-error003`
- `http://www.w3.org/2013/RDFXMLTests/#rdfms-empty-property-elements-test003`
- `http://www.w3.org/2013/RDFXMLTests/#rdfms-empty-property-elements-test009`
- `http://www.w3.org/2013/RDFXMLTests/#rdfms-xml-literal-namespaces-test001`
- `http://www.w3.org/2013/RDFXMLTests/#rdfms-xml-literal-namespaces-test002`
- `http://www.w3.org/2013/RDFXMLTests/#rdfms-xmllang-test001`
- `http://www.w3.org/2013/RDFXMLTests/#rdfms-xmllang-test002`

**Comment by aucampia** [comment]
The tests seem to pass without problem, and at least some of the coverage that was lost comes back. I don't see any reports for these tests at <https://w3c.github.io/rdf-tests/rdf-xml/reports/> but I do see some reports in the older reports <https://www.w3.org/2003/11/results/rdf-core-tests>.

**Comment by afs** [comment]
Looking at "git blame" in the github UI, the tests arrived at rdf-test CG like that.

And were published like that: https://www.w3.org/2013/RDFXMLTests/ shows last change "2014-12-15 10:56".

They might have something else in common but they are all `parseType="Literal"` and that is [non-normative at RDF 1.1](https://www.w3.org/TR/rdf-syntax-grammar/#section-Syntax-XML-literals) as noted in Appendix B, point 13.

**Comment by aucampia** [comment]
> They might have something else in common but they are all `parseType="Literal"` and that is [non-normative at RDF 1.1](https://www.w3.org/TR/rdf-syntax-grammar/#section-Syntax-XML-literals) as noted in Appendix B, point 13.

Thanks, I was not aware that it was non normative, and that explains why they are commented out, closing this issue.

**Comment by gkellogg** [comment]
> They might have something else in common but they are all `parseType="Literal"` and that is [non-normative at RDF 1.1](https://www.w3.org/TR/rdf-syntax-grammar/#section-Syntax-XML-literals) as noted in Appendix B, point 13.

XMLLiterals in both RDF/XML and RDFa+XHTML have quite complicated processing models due to the need to create the [Exclusive Canonical](https://www.w3.org/TR/xml-exc-c14n/) representation, which is likely why it wasn't standardized for 1.1.

Interestingly, JSON-LD introduced [rdf:JSON](https://www.w3.org/TR/json-ld11/#the-rdf-json-datatype) which serves a similar purpose to `rdf:XMLLiteral` providing a means of canonically representing a JSON literal, but it is not burdened with the same problems of maintaining namespace declarations.
