### ISSUE TITLE
Incorrect variable name order in resultset file for 'iri01' test

### ISSUE THREAD

**Issue by wouterbeek** [w3c/rdf-tests#85]
### Observed

According to [SPARQL Query Results XML Format (Second Edition)](https://www.w3.org/TR/rdf-sparql-XMLres/#head):

> The order of the variable names in the sequence is the order of the variable names given to the argument of the SELECT statement in the SPARQL query. If SELECT * is used, the order of the names is undefined.

In the [iri01 query](https://github.com/w3c/rdf-tests/blob/main/sparql11/data-sparql11/functions/iri01.rq) the order of the variable names is `?uri ?iri`.  But in the header of the [corresponding resultset file](https://github.com/w3c/rdf-tests/blob/main/sparql11/data-sparql11/functions/iri01.srx) the order is `?iri ?uri`.

### Expected

The resultset serialization file for the `iri01` test to use the correct variable name order, i.e. `?uri ?iri`.

**Comment by gkellogg** [comment]
Closed via #86.
