### ISSUE TITLE
Univeral Manifest

### ISSUE THREAD

**Issue by jeswr** [w3c/rdf-tests#92]
Would it be possible to have a universal rdf-tests manifest that points to the manifest of each test-suite as a sub-manifest. That way tools like https://github.com/rubensworks/rdf-test-suite.js/ would be discover relevant test suites based on that single manifest rather than each tool using it having to specify the manifests urls to use for each tests case.

Ideally there would also be a universal manifest for all test-suites still in flux (e.g. RDF-Star and the renewed N3 effort https://w3c.github.io/N3/spec/).

**Comment by gkellogg** [comment]
I could see a manifest for all RDF tests and another for SPARQL (which pretty much already exists).

We have to decide on how to handle experimental or newly proposed tests; additional manifests is one way to go, another would be to add some form of an aspect to each test entry. JSON-LD took the unified manifest approach and added `options` which could include `specVersion` and some other properties.

**Comment by jeswr** [comment]
Personally I would be in favor of having something similar to `rdft:Approval` that is applied to entire test suites or manifests rather than individual tests. The possible status' that I would be in favour of are

  - `rdft:WGApprovedTestSuite`
  - `rdft:WGProposedTestSuite`
  - `rdft:CGApprovedTestSuite`
  - `rdft:CGProposedTestSuite`
  - `rdft:RejectedTestSuite` (not likely to be used?)

**Comment by afs** [comment]
Tests are likely to be developed within a working group repo (for IP & copyright reasons + github repo access reasons).
