### ISSUE TITLE
Proposed Turtle Test

### ISSUE THREAD

**Issue by jeswr** [w3c/rdf-tests#93]
I just discovered the following test case from the N3 test suite to be a bug in N3.js; might be worth adding to the Turtle test suite (in our instance the parser struggled with the `a` abbreviation being within a blankNode in a list.

```ttl
@prefix : <http://example.org/>
:a :b ([ a :mother ]).
```

**Comment by gkellogg** [comment]
Care to do a PR?

**Comment by jeswr** [comment]
Will do later today :)

**Comment by afs** [comment]
As given, there is a lack of DOT on the end of the `@prefix` line.
